# Generated by Django 5.0.7 on 2024-07-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
