# Generated by Django 5.0.7 on 2024-07-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='image_url',
        ),
    ]
