# Generated by Django 5.0.7 on 2024-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
