# Generated by Django 5.0.7 on 2024-08-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postmodel_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='summary',
        ),
    ]
