# Generated by Django 5.0.7 on 2024-08-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_postmodel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image_url',
        ),
    ]
