# Generated by Django 5.0.7 on 2024-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_postmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='default_blog.png', upload_to='Images'),
        ),
    ]
