# Generated by Django 5.0.7 on 2024-08-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_postmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='image_url',
        ),
    ]
